import { ElectricalProduct } from "./api";

export const FALLBACK_PRODUCTS: ElectricalProduct[] = [
  // ==========================================
  // LIGHTING
  // ==========================================
  {
    id: "prod_led_bulb_01",
    image_url: "/products/existing/prod_led_bulb_01.svg",
    image: "/products/existing/prod_led_bulb_01.svg",
    image_source: "LOCAL",
    image_status: "IMAGE_AVAILABLE",
    productId: "ELEC-LGT-01",
    name: "Philips Stellar 9W LED Bulb (Cool Day White)",
    category: "Lighting",
    subcategory: "LED Bulbs",
    price: 149,
    discountPrice: 129,
    currency: "INR",
    stock: 200,
    in_stock: true,
    rating: 4.8,
    reviews_count: 640,
    badge: "Bestseller",
    description: "Energy-efficient 9W B22 LED bulb offering 900 Lumens crystal clear cool daylight with surge protection up to 4kV.",
    specs: {
      Wattage: "9W",
      "Cap Fitting": "B22",
      Lumens: "900 lm",
      Lifespan: "25,000 Hours",
      "Color Temp": "6500K Cool White",
      Warranty: "2 Years",
    },
  },
  {
    id: "prod_led_bulb_12w",
    image_url: "/products/existing/prod_led_bulb_12w.svg",
    image: "/products/existing/prod_led_bulb_12w.svg",
    image_source: "LOCAL",
    image_status: "IMAGE_AVAILABLE",
    productId: "ELEC-LGT-02",
    name: "Havells Glaze 12W High-Beam LED Bulb",
    category: "Lighting",
    subcategory: "LED Bulbs",
    price: 249,
    discountPrice: 199,
    currency: "INR",
    stock: 150,
    in_stock: true,
    rating: 4.7,
    reviews_count: 480,
    badge: "High Brightness",
    description: "High-lumen 12W LED bulb with wide 220° beam angle and anti-glare frosted diffuser for large rooms.",
    specs: {
      Wattage: "12W",
      "Cap Fitting": "B22 / E27",
      Lumens: "1300 lm",
      CRI: "> 85",
      Warranty: "2 Years",
    },
  },
  {
    id: "prod_smart_bulb_02",
    image_url: "/products/existing/prod_smart_bulb_02.svg",
    image: "/products/existing/prod_smart_bulb_02.svg",
    image_source: "LOCAL",
    image_status: "IMAGE_AVAILABLE",
    productId: "ELEC-LGT-03",
    name: "Wipro Next 20W Smart RGB LED Bulb (WiFi + Alexa)",
    category: "Lighting",
    subcategory: "Smart LED Bulbs",
    price: 1299,
    discountPrice: 999,
    currency: "INR",
    stock: 85,
    in_stock: true,
    rating: 4.7,
    reviews_count: 340,
    badge: "Smart Home",
    description: "16 million colors tunable smart bulb with voice control via Amazon Alexa & Google Home, scheduling, and music sync.",
    specs: {
      Wattage: "20W",
      Connectivity: "WiFi 2.4GHz + BLE",
      Colors: "16 Million RGB Colors",
      "Voice Control": "Alexa / Google Assistant",
      Warranty: "2 Years",
    },
  },
  {
    id: "prod_tube_light_03",
    image_url: "/products/existing/prod_tube_light_03.svg",
    image: "/products/existing/prod_tube_light_03.svg",
    image_source: "LOCAL",
    image_status: "IMAGE_AVAILABLE",
    productId: "ELEC-LGT-04",
    name: "Syska Lumina 36W LED Batten Tube Light (4 Feet)",
    category: "Lighting",
    subcategory: "Batten Tube Lights",
    price: 649,
    discountPrice: 499,
    currency: "INR",
    stock: 120,
    in_stock: true,
    rating: 4.6,
    reviews_count: 210,
    badge: "Super Bright",
    description: "Slim 4-foot LED batten delivering uniform shadow-free lighting with durable polycarbonate housing and high lumen output.",
    specs: {
      Wattage: "36W",
      Length: "4 Feet (1200 mm)",
      Lumens: "3600 lm",
      "Power Factor": "> 0.9",
      Warranty: "2 Years",
    },
  },
  {
    id: "prod_panel_light_04",
    image_url: "/products/existing/prod_panel_light_04.svg",
    image: "/products/existing/prod_panel_light_04.svg",
    image_source: "LOCAL",
    image_status: "IMAGE_AVAILABLE",
    productId: "ELEC-LGT-05",
    name: "Crompton Slim Ray 15W Round LED Recessed Panel Light",
    category: "Lighting",
    subcategory: "Panel Lights",
    price: 549,
    discountPrice: 399,
    currency: "INR",
    stock: 90,
    in_stock: true,
    rating: 4.7,
    reviews_count: 180,
    badge: "Modern Ceiling",
    description: "Ultra-thin recessed ceiling panel light with edge-lit LED technology and anti-glare diffuser for modern interiors.",
    specs: {
      Wattage: "15W",
      Shape: "Round Rimless",
      Cutout: "150 mm",
      "Surge Protection": "2.5 kV",
      Warranty: "2 Years",
    },
  },
  {
    id: "prod_flood_light_05",
    image_url: "/products/existing/prod_flood_light_05.svg",
    image: "/products/existing/prod_flood_light_05.svg",
    image_source: "LOCAL",
    image_status: "IMAGE_AVAILABLE",
    productId: "ELEC-LGT-06",
    name: "Polycab IP66 50W Outdoor Waterproof LED Flood Light",
    category: "Lighting",
    subcategory: "Outdoor Flood Lights",
    price: 1899,
    discountPrice: 1499,
    currency: "INR",
    stock: 45,
    in_stock: true,
    rating: 4.9,
    reviews_count: 110,
    badge: "Industrial Grade",
    description: "Heavy-duty die-cast aluminum waterproof floodlight designed for gardens, parking lots, security illumination, and workshops.",
    specs: {
      Wattage: "50W",
      "Ingress Rating": "IP66 Waterproof",
      Material: "Die-cast Aluminum",
      "Surge Protection": "4 kV",
      Warranty: "3 Years",
    },
  },

  // ==========================================
  // FANS & COOLING
  // ==========================================
  {
    id: "prod_ceiling_fan_01",
    image_url: "/products/existing/prod_ceiling_fan_01.svg",
    image: "/products/existing/prod_ceiling_fan_01.svg",
    image_source: "LOCAL",
    image_status: "IMAGE_AVAILABLE",
    productId: "ELEC-FAN-01",
    name: "Atomberg Renesa 1200mm Smart BLDC Ceiling Fan (Remote)",
    category: "Fans & Cooling",
    subcategory: "BLDC Ceiling Fans",
    price: 4999,
    discountPrice: 3699,
    currency: "INR",
    stock: 60,
    in_stock: true,
    rating: 4.9,
    reviews_count: 850,
    badge: "65% Energy Saving",
    description: "Super energy-efficient BLDC motor ceiling fan with smart remote control, boost mode, sleep timer, and LED speed indicators.",
    specs: {
      "Sweep Size": "1200 mm",
      "Power Consumption": "28W at Highest Speed",
      Speed: "360 RPM",
      "Air Delivery": "235 CMM",
      Control: "Smart IR Remote Control",
      Warranty: "2+1 Years",
    },
  },
  {
    id: "prod_ceiling_fan_02",
    image_url: "/products/existing/prod_ceiling_fan_02.svg",
    image: "/products/existing/prod_ceiling_fan_02.svg",
    image_source: "LOCAL",
    image_status: "IMAGE_AVAILABLE",
    productId: "ELEC-FAN-02",
    name: "Orient Electric Aeroquiet 1200mm Silent Ceiling Fan",
    category: "Fans & Cooling",
    subcategory: "Silent Ceiling Fans",
    price: 6200,
    discountPrice: 4799,
    currency: "INR",
    stock: 35,
    in_stock: true,
    rating: 4.8,
    reviews_count: 420,
    badge: "Whisper Quiet",
    description: "Aerodynamic PU finish fan with curved blades designed for ultra-low noise operation and high air thrust.",
    specs: {
      "Sweep Size": "1200 mm",
      "Noise Level": "Ultra Quiet (45 dB)",
      Speed: "310 RPM",
      Finish: "High Gloss PU Rust-Free",
      Warranty: "2 Years",
    },
  },
  {
    id: "prod_exhaust_fan_03",
    image_url: "/products/existing/prod_exhaust_fan_03.svg",
    image: "/products/existing/prod_exhaust_fan_03.svg",
    image_source: "LOCAL",
    image_status: "IMAGE_AVAILABLE",
    productId: "ELEC-FAN-03",
    name: "Havells Ventil Air DB 200mm Heavy Exhaust Fan",
    category: "Fans & Cooling",
    subcategory: "Exhaust Fans",
    price: 1899,
    discountPrice: 1450,
    currency: "INR",
    stock: 75,
    in_stock: true,
    rating: 4.6,
    reviews_count: 290,
    badge: "High Airflow",
    description: "Durable metal blade exhaust fan with automatic gravity shutters to prevent dust and bird entry, ideal for kitchens and restrooms.",
    specs: {
      "Sweep Size": "200 mm (8 Inch)",
      Speed: "1350 RPM",
      "Shutter Type": "Auto Gravity Louver",
      Body: "Corrosion Resistant Metal",
      Warranty: "2 Years",
    },
  },
  {
    id: "prod_pedestal_fan_04",
    image_url: "/products/existing/prod_pedestal_fan_04.svg",
    image: "/products/existing/prod_pedestal_fan_04.svg",
    image_source: "LOCAL",
    image_status: "IMAGE_AVAILABLE",
    productId: "ELEC-FAN-04",
    name: "Usha Mist Air Icy 400mm Pedestal Fan with Oscillation",
    category: "Fans & Cooling",
    subcategory: "Pedestal Fans",
    price: 3490,
    discountPrice: 2799,
    currency: "INR",
    stock: 40,
    in_stock: true,
    rating: 4.7,
    reviews_count: 310,
    badge: "High Thrust",
    description: "Aerodynamically balanced 3-blade pedestal fan with telescopic height adjustment and thermal overload motor protection.",
    specs: {
      "Sweep Size": "400 mm",
      "Air Delivery": "75 CMM",
      Motor: "100% Copper Winding",
      Height: "Adjustable 1150-1350 mm",
      Warranty: "2 Years",
    },
  },
  {
    id: "prod_tower_fan_05",
    image_url: "/products/existing/prod_tower_fan_05.svg",
    image: "/products/existing/prod_tower_fan_05.svg",
    image_source: "LOCAL",
    image_status: "IMAGE_AVAILABLE",
    productId: "ELEC-FAN-05",
    name: "Bajaj Windfall 750mm Compact Tower Fan (3-Speed)",
    category: "Fans & Cooling",
    subcategory: "Tower Fans",
    price: 4499,
    discountPrice: 3299,
    currency: "INR",
    stock: 30,
    in_stock: true,
    rating: 4.5,
    reviews_count: 160,
    badge: "Space Saver",
    description: "Sleek compact tower fan with wide 80° oscillation, 3-speed rotary controller, and noiseless cross-flow blower.",
    specs: {
      Height: "750 mm",
      Oscillation: "80° Motorized Swivel",
      "Blower Type": "Low-Noise Cross Flow",
      Wattage: "45W",
      Warranty: "1 Year",
    },
  },

  // ==========================================
  // LAPTOPS & COMPUTERS
  // ==========================================
  {
    id: "prod_laptop_biz_01",
    image_url: "/products/existing/prod_laptop_biz_01.svg",
    image: "/products/existing/prod_laptop_biz_01.svg",
    image_source: "LOCAL",
    image_status: "IMAGE_AVAILABLE",
    productId: "COMP-LPT-01",
    name: "ProBook Ultra Slim 15.6\" Business Laptop (Core i7, 16GB, 1TB SSD)",
    category: "Laptops & Computers",
    subcategory: "Business Laptops",
    price: 74999,
    discountPrice: 65999,
    currency: "INR",
    stock: 25,
    in_stock: true,
    rating: 4.9,
    reviews_count: 215,
    badge: "Enterprise Pro",
    description: "Ultra-fast enterprise business laptop featuring Intel Core i7 13th Gen processor, 16GB DDR5 memory, 1TB NVMe PCIe 4.0 SSD, fingerprint security, and 12-hour fast-charge battery.",
    specs: {
      Processor: "Intel Core i7-1355U (10 Cores, up to 5.0 GHz)",
      RAM: "16GB DDR5 5200MHz",
      Storage: "1TB PCIe 4.0 NVMe M.2 SSD",
      Display: "15.6\" FHD (1920x1080) IPS Anti-Glare 300 Nits",
      Graphics: "Intel Iris Xe Graphics",
      Battery: "54Wh with 65W Type-C Fast Charger",
      OS: "Windows 11 Pro Genuine Pre-installed",
      Weight: "1.65 kg",
      Warranty: "3 Years Onsite Commercial Warranty",
    },
  },
  {
    id: "prod_laptop_workstation_02",
    image_url: "/products/existing/prod_laptop_workstation_02.svg",
    image: "/products/existing/prod_laptop_workstation_02.svg",
    image_source: "LOCAL",
    image_status: "IMAGE_AVAILABLE",
    productId: "COMP-LPT-02",
    name: "Precision Workstation 16\" (Core i9, 32GB RAM, RTX 4070, 2TB SSD)",
    category: "Laptops & Computers",
    subcategory: "Creator & CAD Workstations",
    price: 145000,
    discountPrice: 129999,
    currency: "INR",
    stock: 12,
    in_stock: true,
    rating: 5.0,
    reviews_count: 88,
    badge: "Heavy Computing",
    description: "High-performance workstation engineered for 3D modeling, deep learning, video rendering, and heavy multitasking. Features dedicated NVIDIA GeForce RTX 4070 8GB GDDR6 GPU.",
    specs: {
      Processor: "Intel Core i9-13900H (14 Cores, 20 Threads, up to 5.4 GHz)",
      RAM: "32GB DDR5 5600MHz (Expandable to 64GB)",
      Storage: "2TB NVMe PCIe Gen4 Ultra-Speed SSD",
      Display: "16.0\" QHD+ (2560x1600) 165Hz 100% DCI-P3 500 Nits",
      GPU: "NVIDIA GeForce RTX 4070 (8GB GDDR6 VRAM, 140W TGP)",
      Cooling: "Dual Vapor Chamber with Liquid Metal",
      OS: "Windows 11 Pro",
      Weight: "2.1 kg",
      Warranty: "3 Years Comprehensive Onsite + ADP",
    },
  },
  {
    id: "prod_laptop_student_03",
    image_url: "/products/existing/prod_laptop_student_03.svg",
    image: "/products/existing/prod_laptop_student_03.svg",
    image_source: "LOCAL",
    image_status: "IMAGE_AVAILABLE",
    productId: "COMP-LPT-03",
    name: "ZenBook Lite 14\" Portable Ultrabook (Ryzen 5, 16GB, 512GB SSD)",
    category: "Laptops & Computers",
    subcategory: "Student & Home Ultrabooks",
    price: 49999,
    discountPrice: 42999,
    currency: "INR",
    stock: 45,
    in_stock: true,
    rating: 4.8,
    reviews_count: 310,
    badge: "Best Value",
    description: "Featherlight all-metal ultrabook with AMD Ryzen 5 7530U processor, 16GB LPDDR4X RAM, backlit keyboard, and vibrant OLED display with all-day battery life.",
    specs: {
      Processor: "AMD Ryzen 5 7530U (6 Cores, 12 Threads, up to 4.5 GHz)",
      RAM: "16GB LPDDR4X Dual Channel",
      Storage: "512GB M.2 NVMe SSD",
      Display: "14.0\" Full HD OLED (1920x1080) 100% sRGB 400 Nits",
      Battery: "50Wh with 14 Hours Run-Time",
      Weight: "1.38 kg",
      OS: "Windows 11 Home + MS Office 2021",
      Warranty: "1 Year International",
    },
  },
  {
    id: "prod_laptop_gaming_04",
    image_url: "/products/existing/prod_laptop_gaming_04.svg",
    image: "/products/existing/prod_laptop_gaming_04.svg",
    image_source: "LOCAL",
    image_status: "IMAGE_AVAILABLE",
    productId: "COMP-LPT-04",
    name: "Titan Strix 15.6\" High-FPS Gaming Laptop (Core i7, RTX 4060, 16GB, 1TB)",
    category: "Laptops & Computers",
    subcategory: "Gaming Laptops",
    price: 109999,
    discountPrice: 94999,
    currency: "INR",
    stock: 18,
    in_stock: true,
    rating: 4.9,
    reviews_count: 145,
    badge: "144Hz Refresh",
    description: "Built for esports and extreme gaming performance. Equipped with Intel Core i7 13th Gen, NVIDIA RTX 4060 8GB GPU with MUX Switch, 4-zone RGB keyboard, and 144Hz panel.",
    specs: {
      Processor: "Intel Core i7-13650HX (14 Cores, 24M Cache, up to 4.9 GHz)",
      RAM: "16GB DDR5 4800MHz (2x Slots)",
      Storage: "1TB PCIe Gen4 SSD",
      GPU: "NVIDIA GeForce RTX 4060 8GB GDDR6 (140W Max TGP)",
      Display: "15.6\" FHD 144Hz IPS 100% sRGB Adaptive-Sync",
      OS: "Windows 11 Home",
      Warranty: "2 Years Premium Support",
    },
  },
  {
    id: "prod_laptop_convertible_05",
    image_url: "/products/existing/prod_laptop_convertible_05.svg",
    image: "/products/existing/prod_laptop_convertible_05.svg",
    image_source: "LOCAL",
    image_status: "IMAGE_AVAILABLE",
    productId: "COMP-LPT-05",
    name: "FlexiTouch 2-in-1 14\" Touchscreen Convertible Laptop (Stylus Included)",
    category: "Laptops & Computers",
    subcategory: "2-in-1 Touchscreen Laptops",
    price: 68999,
    discountPrice: 58999,
    currency: "INR",
    stock: 20,
    in_stock: true,
    rating: 4.7,
    reviews_count: 95,
    badge: "Touch & Stylus",
    description: "Versatile 360-degree rotating touchscreen laptop with active digital stylus pen, aluminum body, Harman speakers, and fingerprint unlock.",
    specs: {
      Processor: "Intel Core i5-1335U (10 Cores, up to 4.6 GHz)",
      RAM: "16GB LPDDR5 4800MHz",
      Storage: "512GB NVMe SSD",
      Display: "14.0\" WUXGA (1920x1200) Touchscreen IPS with Gorilla Glass",
      Accessories: "Active Rechargeable Stylus Pen Included",
      Battery: "52.5Wh Fast Charging",
      OS: "Windows 11 Home",
      Warranty: "2 Years Onsite",
    },
  },
  {
    id: "prod_desktop_mini_06",
    image_url: "/products/existing/prod_desktop_mini_06.svg",
    image: "/products/existing/prod_desktop_mini_06.svg",
    image_source: "LOCAL",
    image_status: "IMAGE_AVAILABLE",
    productId: "COMP-LPT-06",
    name: "Compact Tower Micro Desktop PC (Core i7, 32GB RAM, 1TB SSD, WiFi 6E)",
    category: "Laptops & Computers",
    subcategory: "Desktop Workstations",
    price: 59999,
    discountPrice: 51999,
    currency: "INR",
    stock: 22,
    in_stock: true,
    rating: 4.8,
    reviews_count: 67,
    badge: "Micro Workstation",
    description: "Compact 1-Litre commercial desktop workstation engineered for multi-monitor setups, corporate offices, accounting, and development environments.",
    specs: {
      Processor: "Intel Core i7-13700T (16 Cores, 24 Threads)",
      RAM: "32GB DDR5 4800MHz",
      Storage: "1TB PCIe Gen4 SSD + Secondary M.2 Slot Free",
      Connectivity: "WiFi 6E + Bluetooth 5.3 + Dual DisplayPort + 2.5G LAN",
      Dimensions: "179 x 182 x 36 mm (Ultra-Compact)",
      OS: "Windows 11 Pro Genuine",
      Warranty: "3 Years Commercial Next Business Day Onsite",
    },
  },

  // ==========================================
  // COMPUTER ACCESSORIES
  // ==========================================
  {
    id: "prod_acc_mech_keyboard_01",
    image_url: "/products/existing/prod_acc_mech_keyboard_01.svg",
    image: "/products/existing/prod_acc_mech_keyboard_01.svg",
    image_source: "LOCAL",
    image_status: "IMAGE_AVAILABLE",
    productId: "COMP-ACC-01",
    name: "Keychron K2 V2 Wireless Mechanical Keyboard (RGB, Hot-Swappable)",
    category: "Computer Accessories",
    subcategory: "Mechanical Keyboards",
    price: 8499,
    discountPrice: 6999,
    currency: "INR",
    stock: 45,
    in_stock: true,
    rating: 4.9,
    reviews_count: 320,
    badge: "Hot Swappable",
    description: "Compact 75% layout wireless mechanical keyboard with Gateron G Pro Red linear switches, Mac & Windows keycaps, 4000mAh battery, and customizable RGB backlighting.",
    specs: {
      Layout: "75% (84 Keys)",
      Switches: "Gateron G Pro Red / Brown",
      Connectivity: "Bluetooth 5.1 & Type-C Wired",
      Battery: "4000 mAh (up to 240 hours)",
      Compatibility: "Windows / macOS / iOS / Android",
      Warranty: "1 Year",
    },
  },
  {
    id: "prod_acc_ergo_mouse_02",
    image_url: "/products/existing/prod_acc_ergo_mouse_02.svg",
    image: "/products/existing/prod_acc_ergo_mouse_02.svg",
    image_source: "LOCAL",
    image_status: "IMAGE_AVAILABLE",
    productId: "COMP-ACC-02",
    name: "Logitech MX Master 3S Advanced Wireless Ergonomic Mouse",
    category: "Computer Accessories",
    subcategory: "Wireless Mice",
    price: 9995,
    discountPrice: 8495,
    currency: "INR",
    stock: 55,
    in_stock: true,
    rating: 5.0,
    reviews_count: 512,
    badge: "Top Productivity",
    description: "Premier productivity mouse with 8K DPI track-on-glass optical sensor, MagSpeed electromagnetic scroll wheel, quiet click switches, and USB-C fast charging.",
    specs: {
      Sensor: "8000 DPI Darkfield High Precision",
      Clicks: "90% Quieter Acoustic Switches",
      Scroll: "MagSpeed 1000 Lines/sec Wheel",
      Battery: "70 Days on Full Charge",
      MultiDevice: "Connect up to 3 Devices with Flow",
      Warranty: "1 Year",
    },
  },
  {
    id: "prod_acc_monitor_03",
    image_url: "/products/existing/prod_acc_monitor_03.svg",
    image: "/products/existing/prod_acc_monitor_03.svg",
    image_source: "LOCAL",
    image_status: "IMAGE_AVAILABLE",
    productId: "COMP-ACC-03",
    name: "LG 27\" UltraFine 4K UHD IPS Monitor (USB-C 65W PD, HDR400)",
    category: "Computer Accessories",
    subcategory: "Monitors",
    price: 32000,
    discountPrice: 26999,
    currency: "INR",
    stock: 20,
    in_stock: true,
    rating: 4.8,
    reviews_count: 180,
    badge: "4K Color Accurate",
    description: "Professional 27-inch 4K UHD IPS display offering 99% sRGB color gamut, HDR 400 support, height-adjustable stand, and single USB-C cable for 65W power delivery and video.",
    specs: {
      Resolution: "3840 x 2160 (4K UHD)",
      Panel: "IPS with 178° Viewing Angle",
      Color: "99% sRGB, VESA DisplayHDR 400",
      Ports: "USB-C (65W PD) + 2x HDMI 2.0 + DisplayPort",
      Stand: "Height / Tilt / Pivot Adjustable",
      Warranty: "3 Years Onsite",
    },
  },
  {
    id: "prod_acc_dock_04",
    image_url: "/products/existing/prod_acc_dock_04.svg",
    image: "/products/existing/prod_acc_dock_04.svg",
    image_source: "LOCAL",
    image_status: "IMAGE_AVAILABLE",
    productId: "COMP-ACC-04",
    name: "Anker 13-in-1 Triple Display Thunderbolt 4 Docking Station (100W PD)",
    category: "Computer Accessories",
    subcategory: "Docking Stations",
    price: 18999,
    discountPrice: 15499,
    currency: "INR",
    stock: 30,
    in_stock: true,
    rating: 4.9,
    reviews_count: 94,
    badge: "Triple Display",
    description: "High-speed 40Gbps Thunderbolt 4 docking hub supporting triple 4K monitors, Gigabit Ethernet, SD card slots, USB 3.2 10Gbps ports, and 100W host charging.",
    specs: {
      Bandwidth: "40Gbps Thunderbolt 4 / USB4",
      Displays: "Triple 4K@60Hz or Single 8K@30Hz",
      HostPower: "100W Max Laptop Power Delivery",
      PortsCount: "13 Comprehensive Expansion Ports",
      Warranty: "2 Years",
    },
  },
  {
    id: "prod_acc_ssd_05",
    image_url: "/products/existing/prod_acc_ssd_05.svg",
    image: "/products/existing/prod_acc_ssd_05.svg",
    image_source: "LOCAL",
    image_status: "IMAGE_AVAILABLE",
    productId: "COMP-ACC-05",
    name: "Samsung T7 Shield 2TB Rugged External Portable NVMe SSD (1050MB/s)",
    category: "Computer Accessories",
    subcategory: "External Storage",
    price: 19999,
    discountPrice: 15999,
    currency: "INR",
    stock: 40,
    in_stock: true,
    rating: 4.9,
    reviews_count: 280,
    badge: "IP65 Rugged",
    description: "Heavy-duty drop-resistant IP65 dust and water-resistant external SSD with sequential read/write speeds up to 1,050 MB/s and hardware AES 256-bit encryption.",
    specs: {
      Capacity: "2TB",
      Interface: "USB 3.2 Gen 2 (10 Gbps)",
      Speed: "Up to 1,050 MB/s Read / 1,000 MB/s Write",
      Durability: "IP65 Water/Dust Resistant + 3-meter Drop Proof",
      Security: "AES 256-bit Hardware Encryption",
      Warranty: "3 Years",
    },
  },
  {
    id: "prod_acc_router_06",
    image_url: "/products/existing/prod_acc_router_06.svg",
    image: "/products/existing/prod_acc_router_06.svg",
    image_source: "LOCAL",
    image_status: "IMAGE_AVAILABLE",
    productId: "COMP-ACC-06",
    name: "TP-Link Archer AXE75 Tri-Band WiFi 6E Gigabit Gaming Router (5400Mbps)",
    category: "Computer Accessories",
    subcategory: "Networking & Routers",
    price: 14999,
    discountPrice: 11999,
    currency: "INR",
    stock: 25,
    in_stock: true,
    rating: 4.8,
    reviews_count: 150,
    badge: "Tri-Band 6GHz",
    description: "Next-gen Tri-Band WiFi 6E router opening up the clean 6GHz band with 6 high-gain antennas, 1.7GHz Quad-Core CPU, and HomeShield security.",
    specs: {
      Bands: "6GHz (2402 Mbps) + 5GHz (2402 Mbps) + 2.4GHz (574 Mbps)",
      Processor: "1.7 GHz 64-bit Quad-Core CPU",
      Antennas: "6x High-Gain External Antennas",
      Ports: "1x Gigabit WAN + 4x Gigabit LAN + USB 3.0",
      Capacity: "Connect up to 200+ Devices with Zero Congestion",
      Warranty: "3 Years",
    },
  },

  // ==========================================
  // POWER & CABLES
  // ==========================================
  {
    id: "prod_spike_guard_01",
    image_url: "/products/existing/prod_spike_guard_01.svg",
    image: "/products/existing/prod_spike_guard_01.svg",
    image_source: "LOCAL",
    image_status: "IMAGE_AVAILABLE",
    productId: "ELEC-PWR-01",
    name: "Goldmedal Curve Plus 6-Way Surge Protector & Extension Strip",
    category: "Power & Cables",
    subcategory: "Surge Protectors",
    price: 1250,
    discountPrice: 899,
    currency: "INR",
    stock: 140,
    in_stock: true,
    rating: 4.8,
    reviews_count: 530,
    badge: "Surge Protected",
    description: "Heavy-duty 6 universal socket extension board with individual LED power switches, built-in MOV surge suppressor, and 2.5-meter ISI certified fire-retardant cable.",
    specs: {
      Sockets: "6 Universal Sockets with Safety Shutters",
      "Cord Length": "2.5 Meters Heavy Copper",
      "Surge Energy Rating": "700 Joules",
      "Max Load": "2500W (10A 250V)",
      Warranty: "2 Years",
    },
  },
  {
    id: "prod_industrial_reel_02",
    image_url: "/products/existing/prod_industrial_reel_02.svg",
    image: "/products/existing/prod_industrial_reel_02.svg",
    image_source: "LOCAL",
    image_status: "IMAGE_AVAILABLE",
    productId: "ELEC-PWR-02",
    name: "Havells Industrial Heavy Cable Reel 25-Meter (16A / 3500W)",
    category: "Power & Cables",
    subcategory: "Extension Reels",
    price: 3499,
    discountPrice: 2899,
    currency: "INR",
    stock: 35,
    in_stock: true,
    rating: 4.9,
    reviews_count: 140,
    badge: "16A Heavy Duty",
    description: "Rugged metal drum extension reel with thermal cut-out overload protection, ergonomic winding handle, and 25 meters of heavy-gauge 3-core copper cable.",
    specs: {
      Length: "25 Meters",
      Rating: "16A 250V (3500W Max Load)",
      Sockets: "4x 16A Shuttered Outlets",
      Protection: "Thermal Cutout Reset Switch",
      Warranty: "2 Years",
    },
  },
  {
    id: "prod_copper_wire_03",
    image_url: "/products/existing/prod_copper_wire_03.svg",
    image: "/products/existing/prod_copper_wire_03.svg",
    image_source: "LOCAL",
    image_status: "IMAGE_AVAILABLE",
    productId: "ELEC-PWR-03",
    name: "Polycab 2.5 sq.mm Flame Retardant FRLS House Wire (90m Reel)",
    category: "Power & Cables",
    subcategory: "Electrical Wiring",
    price: 2650,
    discountPrice: 2199,
    currency: "INR",
    stock: 80,
    in_stock: true,
    rating: 4.9,
    reviews_count: 310,
    badge: "100% Pure Copper",
    description: "Electrolytic grade 99.97% pure bare copper conductor with Flame Retardant Low Smoke (FRLS) insulation for residential and commercial electrical wiring.",
    specs: {
      Gauge: "2.5 sq.mm",
      Length: "90 Meters Standard Coil",
      Insulation: "FRLS PVC Grade",
      Certification: "IS:694 & CE Certified",
      Warranty: "10 Years Manufacturer Warranty",
    },
  },

  // ==========================================
  // SWITCHES & WIRING
  // ==========================================
  {
    id: "prod_smart_touch_switch_01",
    image_url: "/products/existing/prod_smart_touch_switch_01.svg",
    image: "/products/existing/prod_smart_touch_switch_01.svg",
    image_source: "LOCAL",
    image_status: "IMAGE_AVAILABLE",
    productId: "ELEC-SWT-01",
    name: "Legrand Arteor 4-Gang Smart Touch Glass Switchboard (WiFi/App)",
    category: "Switches & Wiring",
    subcategory: "Smart Switches",
    price: 4999,
    discountPrice: 3899,
    currency: "INR",
    stock: 45,
    in_stock: true,
    rating: 4.8,
    reviews_count: 175,
    badge: "Smart Home",
    description: "Toughened scratch-resistant crystal glass touch panel with backlit capacitive indicators, WiFi smartphone control, timer routines, and Alexa/Google Home voice sync.",
    specs: {
      Gangs: "4 Capacitive Touch Channels",
      Plate: "Tempered Crystal Glass",
      Connectivity: "WiFi 2.4GHz (No Hub Required)",
      "Voice Support": "Alexa & Google Assistant",
      Warranty: "2 Years",
    },
  },
  {
    id: "prod_mcb_double_pole_02",
    image_url: "/products/existing/prod_mcb_double_pole_02.svg",
    image: "/products/existing/prod_mcb_double_pole_02.svg",
    image_source: "LOCAL",
    image_status: "IMAGE_AVAILABLE",
    productId: "ELEC-SWT-02",
    name: "Schneider Electric Acti9 32A Double Pole C-Curve MCB (10kA)",
    category: "Switches & Wiring",
    subcategory: "Circuit Breakers & MCBs",
    price: 890,
    discountPrice: 699,
    currency: "INR",
    stock: 110,
    in_stock: true,
    rating: 4.9,
    reviews_count: 240,
    badge: "Industrial Safety",
    description: "High-breaking capacity miniature circuit breaker engineered for reliable overload and short-circuit protection of air conditioners, inverters, and main distributions.",
    specs: {
      Poles: "2 Pole (DP)",
      "Rated Current": "32 Ampere",
      "Breaking Capacity": "10 kA",
      Curve: "C-Curve (5-10 In)",
      Warranty: "3 Years",
    },
  },

  // ==========================================
  // KITCHEN APPLIANCES
  // ==========================================
  {
    id: "prod_induction_cooktop_01",
    image_url: "/products/existing/prod_induction_cooktop_01.svg",
    image: "/products/existing/prod_induction_cooktop_01.svg",
    image_source: "LOCAL",
    image_status: "IMAGE_AVAILABLE",
    productId: "ELEC-KTN-01",
    name: "Prestige Iris 2000W Smart Induction Cooktop with Indian Menus",
    category: "Kitchen Appliances",
    subcategory: "Induction Cooktops",
    price: 3895,
    discountPrice: 2899,
    currency: "INR",
    stock: 50,
    in_stock: true,
    rating: 4.7,
    reviews_count: 460,
    badge: "Top Seller",
    description: "High-efficiency 2000W induction stove with anti-magnetic ceramic glass plate, automatic voltage regulator, dual heat sensors, and one-touch Indian cooking presets.",
    specs: {
      Wattage: "2000W Fast Heating",
      Plate: "Full Ceramic Crystal Surface",
      Presets: "Dosa, Chapati, Curry, Milk Boil, Idli",
      Safety: "Auto-Off on Vessel Removal",
      Warranty: "1 Year Complete Warranty",
    },
  },
  {
    id: "prod_electric_kettle_02",
    image_url: "/products/existing/prod_electric_kettle_02.svg",
    image: "/products/existing/prod_electric_kettle_02.svg",
    image_source: "LOCAL",
    image_status: "IMAGE_AVAILABLE",
    productId: "ELEC-KTN-02",
    name: "Havells Aqua Plus 1.2L Double-Wall Stainless Steel Electric Kettle",
    category: "Kitchen Appliances",
    subcategory: "Electric Kettles",
    price: 2199,
    discountPrice: 1599,
    currency: "INR",
    stock: 65,
    in_stock: true,
    rating: 4.8,
    reviews_count: 320,
    badge: "Cool Touch",
    description: "Double-wall insulated cool-touch 304 food-grade stainless steel electric kettle with 360° cordless swivel base and dry-boil safety auto cutoff.",
    specs: {
      Capacity: "1.2 Litres",
      Wattage: "1500W Fast Boil",
      Body: "304 Food-Grade Stainless Steel Inner",
      Safety: "Auto Cutoff & Boil-Dry Protection",
      Warranty: "2 Years",
    },
  },

  // ==========================================
  // INVERTERS & HEAVY POWER
  // ==========================================
  {
    id: "prod_inverter_sine_01",
    image_url: "/products/existing/prod_inverter_sine_01.svg",
    image: "/products/existing/prod_inverter_sine_01.svg",
    image_source: "LOCAL",
    image_status: "IMAGE_AVAILABLE",
    productId: "ELEC-INV-01",
    name: "Luminous Zelio+ 1100 Pure Sine Wave Home UPS Inverter",
    category: "Inverters & Heavy Power",
    subcategory: "Pure Sine Wave Inverters",
    price: 8499,
    discountPrice: 6799,
    currency: "INR",
    stock: 28,
    in_stock: true,
    rating: 4.9,
    reviews_count: 380,
    badge: "Smart Display",
    description: "Intelligent 32-bit DSP processor home inverter with intuitive LCD display showing backup time in hours, battery charge percentage, and bypass switch for appliances.",
    specs: {
      Capacity: "900 VA / 756 Watts",
      Waveform: "Pure Sine Wave (Safe for Electronics)",
      Display: "Intuitive LCD Screen with Backup Timer",
      Protection: "Short Circuit, Overload & Reverse Polarity",
      Warranty: "2 Years",
    },
  },
  {
    id: "prod_tubular_battery_02",
    image_url: "/products/existing/prod_tubular_battery_02.svg",
    image: "/products/existing/prod_tubular_battery_02.svg",
    image_source: "LOCAL",
    image_status: "IMAGE_AVAILABLE",
    productId: "ELEC-INV-02",
    name: "Exide InvaMaster 150Ah Tall Tubular Inverter Battery",
    category: "Inverters & Heavy Power",
    subcategory: "Inverter Batteries",
    price: 15499,
    discountPrice: 12999,
    currency: "INR",
    stock: 20,
    in_stock: true,
    rating: 4.8,
    reviews_count: 220,
    badge: "Heavy Duty",
    description: "Ultra low-maintenance heavy-duty tall tubular lead-acid battery engineered for deep discharge recovery and long power outages in harsh climate conditions.",
    specs: {
      Capacity: "150 Ah @ C20",
      Type: "Tall Tubular Deep Cycle",
      Electrolyte: "Level Float Indicators Included",
      Warranty: "36+18 Months Pro-Rata Warranty",
    },
  },
];
