import datetime
from decimal import Decimal
from typing import Any

from sqlalchemy import or_, select
from sqlalchemy.orm import Session

from app.database import SessionLocal
from app.models.transaction import Product


# Comprehensive Catalog for Electrical, Laptops & Computer Accessories
CATALOG_ITEMS: list[dict[str, Any]] = [
    # ==========================================
    # LIGHTING
    # ==========================================
    {
        "id": "prod_led_bulb_01",
        "productId": "ELEC-LGT-01",
        "name": "Philips Stellar 9W LED Bulb (Cool Day White)",
        "category": "Lighting",
        "subcategory": "LED Bulbs",
        "price": 149.00,
        "discountPrice": 129.00,
        "currency": "INR",
        "stock": 200,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.8,
        "reviews_count": 640,
        "reviewCount": 640,
        "badge": "Bestseller",
        "image_url": "https://images.unsplash.com/photo-1550524514-6c70313172ca?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1550524514-6c70313172ca?w=600&auto=format&fit=crop&q=80",
        "description": "Energy-efficient 9W B22 LED bulb offering 900 Lumens crystal clear cool daylight with surge protection up to 4kV.",
        "specs": {
            "Wattage": "9W",
            "Cap Fitting": "B22",
            "Lumens": "900 lm",
            "Lifespan": "25,000 Hours",
            "Color Temp": "6500K Cool White",
            "Warranty": "2 Years",
        },
    },
    {
        "id": "prod_led_bulb_12w",
        "productId": "ELEC-LGT-02",
        "name": "Havells Glaze 12W High-Beam LED Bulb",
        "category": "Lighting",
        "subcategory": "LED Bulbs",
        "price": 249.00,
        "discountPrice": 199.00,
        "currency": "INR",
        "stock": 150,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.7,
        "reviews_count": 480,
        "reviewCount": 480,
        "badge": "High Brightness",
        "image_url": "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=600&auto=format&fit=crop&q=80",
        "description": "High-lumen 12W LED bulb with wide 220° beam angle and anti-glare frosted diffuser for large rooms.",
        "specs": {
            "Wattage": "12W",
            "Cap Fitting": "B22 / E27",
            "Lumens": "1300 lm",
            "CRI": "> 85",
            "Warranty": "2 Years",
        },
    },
    {
        "id": "prod_smart_bulb_02",
        "productId": "ELEC-LGT-03",
        "name": "Wipro Next 20W Smart RGB LED Bulb (WiFi + Alexa)",
        "category": "Lighting",
        "subcategory": "Smart LED Bulbs",
        "price": 1299.00,
        "discountPrice": 999.00,
        "currency": "INR",
        "stock": 85,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.7,
        "reviews_count": 340,
        "reviewCount": 340,
        "badge": "Smart Home",
        "image_url": "https://images.unsplash.com/photo-1558002038-1055907df827?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1558002038-1055907df827?w=600&auto=format&fit=crop&q=80",
        "description": "16 million colors tunable smart bulb with voice control via Amazon Alexa & Google Home, scheduling, and music sync.",
        "specs": {
            "Wattage": "20W",
            "Connectivity": "WiFi 2.4GHz + BLE",
            "Colors": "16 Million RGB Colors",
            "Voice Control": "Alexa / Google Assistant",
            "Warranty": "2 Years",
        },
    },
    {
        "id": "prod_tube_light_03",
        "productId": "ELEC-LGT-04",
        "name": "Havells Glaze 20W T5 LED Batten Tube Light (4 Feet)",
        "category": "Lighting",
        "subcategory": "Tube Lights",
        "price": 499.00,
        "discountPrice": 399.00,
        "currency": "INR",
        "stock": 95,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.6,
        "reviews_count": 180,
        "reviewCount": 180,
        "badge": "Energy Saver",
        "image_url": "https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=600&auto=format&fit=crop&q=80",
        "description": "Ultra-slim 20W batten tube light with uniform light distribution, glare-free optical diffuser, and corrosion-resistant body.",
        "specs": {
            "Length": "4 Feet (1200mm)",
            "Wattage": "20W",
            "Lumens": "2200 lm",
            "Material": "Polycarbonate Extrusion",
            "Warranty": "2 Years",
        },
    },
    {
        "id": "prod_emergency_light_11",
        "productId": "ELEC-LGT-05",
        "name": "Wipro Coral Rechargeable 24-LED Emergency Lantern",
        "category": "Lighting",
        "subcategory": "Emergency Lights",
        "price": 899.00,
        "discountPrice": 749.00,
        "currency": "INR",
        "stock": 80,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.5,
        "reviews_count": 220,
        "reviewCount": 220,
        "badge": "Long Backup",
        "image_url": "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=600&auto=format&fit=crop&q=80",
        "description": "Powerful 24 LED lantern with 3000mAh lithium-ion battery providing up to 8 hours backup, 360-degree illumination, and auto-on on power cut.",
        "specs": {
            "LED Count": "24 High Brightness LEDs",
            "Battery": "3000mAh Li-ion Rechargeable",
            "Backup": "Up to 8 Hours Continuous",
            "Charging Time": "4-5 Hours via USB",
            "Warranty": "1 Year",
        },
    },
    {
        "id": "prod_night_lamp_06",
        "productId": "ELEC-LGT-06",
        "name": "Smart Motion Sensor Plug-in LED Night Lamp",
        "category": "Lighting",
        "subcategory": "Night Lamps",
        "price": 349.00,
        "discountPrice": 299.00,
        "currency": "INR",
        "stock": 110,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.6,
        "reviews_count": 145,
        "reviewCount": 145,
        "badge": "Auto Sensor",
        "image_url": "https://images.unsplash.com/photo-1550524514-6c70313172ca?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1550524514-6c70313172ca?w=600&auto=format&fit=crop&q=80",
        "description": "Dusk-to-dawn automatic motion sensing night lamp for hallways, bedrooms, and staircases. Warm soothing glow.",
        "specs": {
            "Power": "0.5W Ultra Low Power",
            "Sensor": "PIR Infrared + Light Sensor",
            "Color": "Warm White 3000K",
            "Warranty": "1 Year",
        },
    },

    # ==========================================
    # FANS & COOLING
    # ==========================================
    {
        "id": "prod_ceiling_fan_04",
        "productId": "ELEC-FAN-01",
        "name": "Crompton HighBreeze 1200mm Ceiling Fan (Brown)",
        "category": "Fans & Cooling",
        "subcategory": "Ceiling Fans",
        "price": 3499.00,
        "discountPrice": 2999.00,
        "currency": "INR",
        "stock": 42,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.8,
        "reviews_count": 410,
        "reviewCount": 410,
        "badge": "High Air Delivery",
        "image_url": "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=600&auto=format&fit=crop&q=80",
        "description": "High-speed 380 RPM ceiling fan with 100% copper motor, double ball bearing, and aerodynamic ribbed blades.",
        "specs": {
            "Sweep": "1200 mm (48 inches)",
            "Speed": "380 RPM",
            "Air Delivery": "230 CMM",
            "Motor": "100% Copper Winding",
            "Warranty": "2 Years",
        },
    },
    {
        "id": "prod_smart_fan_05",
        "productId": "ELEC-FAN-02",
        "name": "Atomberg Renesa BLDC Smart Ceiling Fan with Remote",
        "category": "Fans & Cooling",
        "subcategory": "BLDC Ceiling Fans",
        "price": 7499.00,
        "discountPrice": 6999.00,
        "currency": "INR",
        "stock": 35,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.9,
        "reviews_count": 620,
        "reviewCount": 620,
        "badge": "5-Star BLDC",
        "image_url": "https://images.unsplash.com/photo-1594918074900-50d4f20f66e0?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1594918074900-50d4f20f66e0?w=600&auto=format&fit=crop&q=80",
        "description": "Super energy-efficient BLDC motor saves up to 65% electricity (consumes only 28W). Comes with smart remote & IoT WiFi app control.",
        "specs": {
            "Motor": "BLDC Inverter Tech",
            "Power": "28W (Saves ₹1500/yr)",
            "Sweep": "1200 mm",
            "Control": "IR Remote & IoT App",
            "Warranty": "3 Years On-Site",
        },
    },
    {
        "id": "prod_table_fan_06",
        "productId": "ELEC-FAN-03",
        "name": "Usha Mist Air 400mm High-Speed Table Fan",
        "category": "Fans & Cooling",
        "subcategory": "Table Fans",
        "price": 1999.00,
        "discountPrice": 1799.00,
        "currency": "INR",
        "stock": 50,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.5,
        "reviews_count": 195,
        "reviewCount": 195,
        "badge": "Compact Air",
        "image_url": "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&auto=format&fit=crop&q=80",
        "description": "Aerodynamically designed 3-blade table fan with 100% copper motor, thermal overload protector, and smooth oscillation.",
        "specs": {
            "Sweep": "400 mm",
            "Speed": "1280 RPM",
            "Power": "55W",
            "Oscillation": "90° Wide Angle",
            "Warranty": "2 Years",
        },
    },
    {
        "id": "prod_exhaust_fan_07",
        "productId": "ELEC-FAN-04",
        "name": "Luminous Vento Deluxe 200mm High-Suction Exhaust Fan",
        "category": "Fans & Cooling",
        "subcategory": "Exhaust Fans",
        "price": 1499.00,
        "discountPrice": 1299.00,
        "currency": "INR",
        "stock": 60,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.6,
        "reviews_count": 130,
        "reviewCount": 130,
        "badge": "Silent Suction",
        "image_url": "https://images.unsplash.com/photo-1517646287270-a5a9ca602e5c?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1517646287270-a5a9ca602e5c?w=600&auto=format&fit=crop&q=80",
        "description": "High air suction exhaust fan for kitchens and bathrooms with automatic back shutters to prevent dust and insects.",
        "specs": {
            "Sweep": "200 mm",
            "Air Suction": "490 CMM",
            "Shutter": "Automatic Louver",
            "Body": "Rust-Proof Polycarbonate",
            "Warranty": "2 Years",
        },
    },
    {
        "id": "prod_wall_fan_08",
        "productId": "ELEC-FAN-05",
        "name": "Orient Electric 450mm High-Speed Wall Fan with Pull Cord",
        "category": "Fans & Cooling",
        "subcategory": "Wall Fans",
        "price": 2299.00,
        "discountPrice": 1999.00,
        "currency": "INR",
        "stock": 40,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.7,
        "reviews_count": 160,
        "reviewCount": 160,
        "badge": "Wall Mount",
        "image_url": "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&auto=format&fit=crop&q=80",
        "description": "Wall mounted oscillating fan with dual pull cord control for speed and oscillation. Aerodynamic resin blades for high thrust.",
        "specs": {
            "Sweep": "450 mm",
            "Speed": "1330 RPM",
            "Mounting": "Wall Mount Bracket Included",
            "Warranty": "2 Years",
        },
    },

    # ==========================================
    # POWER & CABLES
    # ==========================================
    {
        "id": "prod_extension_board_12",
        "productId": "ELEC-PWR-01",
        "name": "Anchor by Panasonic 4-Socket Heavy Extension Board",
        "category": "Power & Cables",
        "subcategory": "Extension Boards",
        "price": 499.00,
        "discountPrice": 429.00,
        "currency": "INR",
        "stock": 110,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.7,
        "reviews_count": 310,
        "reviewCount": 310,
        "badge": "Surge Protected",
        "image_url": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80",
        "description": "4 universal international sockets with individual switch indicators, 2-meter heavy copper cord, and fire-retardant housing.",
        "specs": {
            "Sockets": "4 Universal Sockets",
            "Cord Length": "2 Meters Heavy Duty",
            "Rating": "6A 240V AC",
            "Material": "Flame-Retardant Polycarbonate",
            "Warranty": "1 Year",
        },
    },
    {
        "id": "prod_power_strip_13",
        "productId": "ELEC-PWR-02",
        "name": "Belkin 6-Socket Essential Surge Protector Power Strip",
        "category": "Power & Cables",
        "subcategory": "Power Strips",
        "price": 899.00,
        "discountPrice": 799.00,
        "currency": "INR",
        "stock": 75,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.8,
        "reviews_count": 550,
        "reviewCount": 550,
        "badge": "650 Joules Surge",
        "image_url": "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&auto=format&fit=crop&q=80",
        "description": "650-Joule surge protection protects expensive computers, home theaters, and gaming consoles against voltage spikes and lightning.",
        "specs": {
            "Surge Rating": "650 Joules",
            "Sockets": "6 Grounded Sockets",
            "Max Current": "10A / 2400W",
            "Cable": "2 Meter Heavy Duty",
            "Warranty": "5 Years / Connected Equipment Warranty",
        },
    },
    {
        "id": "prod_usb_cable_15",
        "productId": "ELEC-PWR-03",
        "name": "Boat Rugged Braided USB-C to USB-C 100W Fast Cable",
        "category": "Power & Cables",
        "subcategory": "USB Cables",
        "price": 299.00,
        "discountPrice": 249.00,
        "currency": "INR",
        "stock": 130,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.6,
        "reviews_count": 480,
        "reviewCount": 480,
        "badge": "Nylon Braided",
        "image_url": "https://images.unsplash.com/photo-1541689592655-f5f52825a3b8?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1541689592655-f5f52825a3b8?w=600&auto=format&fit=crop&q=80",
        "description": "Heavy-duty nylon braided 100W Power Delivery cable with 10,000+ bend lifespan and 480Mbps high-speed data transfer.",
        "specs": {
            "Length": "1.5 Meters",
            "Power Rating": "100W (20V/5A)",
            "Connector": "Type-C to Type-C Metal Alloy",
            "Warranty": "2 Years",
        },
    },
    {
        "id": "prod_hdmi_cable_16",
        "productId": "ELEC-PWR-04",
        "name": "Ultra High-Speed 8K 60Hz HDMI 2.1 Braided Cable (2M)",
        "category": "Power & Cables",
        "subcategory": "HDMI Cables",
        "price": 599.00,
        "discountPrice": 499.00,
        "currency": "INR",
        "stock": 90,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.8,
        "reviews_count": 320,
        "reviewCount": 320,
        "badge": "8K 60Hz HDR",
        "image_url": "https://images.unsplash.com/photo-1541689592655-f5f52825a3b8?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1541689592655-f5f52825a3b8?w=600&auto=format&fit=crop&q=80",
        "description": "48Gbps bandwidth 8K HDMI 2.1 cable supporting eARC, Dolby Vision, Dynamic HDR, and VRR for monitors and TVs.",
        "specs": {
            "Resolution": "8K @ 60Hz / 4K @ 120Hz",
            "Bandwidth": "48 Gbps",
            "Length": "2 Meters",
            "Warranty": "2 Years",
        },
    },
    {
        "id": "prod_electrical_wire_20",
        "productId": "ELEC-PWR-05",
        "name": "Finolex 2.5 sq mm Flame Retardant Copper Wire (90m Roll)",
        "category": "Power & Cables",
        "subcategory": "Electrical Wires",
        "price": 1899.00,
        "discountPrice": 1749.00,
        "currency": "INR",
        "stock": 60,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.9,
        "reviews_count": 720,
        "reviewCount": 720,
        "badge": "100% Pure Copper",
        "image_url": "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&auto=format&fit=crop&q=80",
        "description": "100% electrolytic grade multi-strand pure copper wire with lead-free flame-retardant (FR) PVC insulation for house wiring.",
        "specs": {
            "Cross Section": "2.5 sq mm",
            "Length": "90 Meters Standard Roll",
            "Insulation": "Flame Retardant (FR) PVC",
            "Voltage Grade": "1100V",
            "Warranty": "5 Years",
        },
    },
    {
        "id": "prod_power_cable_17",
        "productId": "ELEC-PWR-06",
        "name": "Heavy Duty 16A 3-Pin Computer & Appliance Power Cord (1.8M)",
        "category": "Power & Cables",
        "subcategory": "Power Cables",
        "price": 399.00,
        "discountPrice": 349.00,
        "currency": "INR",
        "stock": 100,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.7,
        "reviews_count": 210,
        "reviewCount": 210,
        "badge": "16A Heavy Duty",
        "image_url": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80",
        "description": "Heavy-duty 16A molded Indian 3-pin plug to IEC C13 socket power cord for computers, servers, UPS, and laser printers.",
        "specs": {
            "Rating": "16A 250V AC",
            "Connector": "IEC C13 to 3-Pin Indian Plug",
            "Length": "1.8 Meters",
            "Warranty": "1 Year",
        },
    },
    {
        "id": "prod_surge_protector_18",
        "productId": "ELEC-PWR-07",
        "name": "Goldmedal Heavy Duty 8-Outlet Master Surge Suppressor",
        "category": "Power & Cables",
        "subcategory": "Surge Protectors",
        "price": 1199.00,
        "discountPrice": 1049.00,
        "currency": "INR",
        "stock": 55,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.8,
        "reviews_count": 280,
        "reviewCount": 280,
        "badge": "EMI/RFI Filter",
        "image_url": "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&auto=format&fit=crop&q=80",
        "description": "8 universal outlets with master switch, EMI/RFI noise filter, overload circuit breaker, and 900 Joules spike absorption.",
        "specs": {
            "Outlets": "8 Universal Sockets",
            "Surge Joules": "900 Joules",
            "Safety": "Thermal Overload Breaker",
            "Warranty": "3 Years",
        },
    },

    # ==========================================
    # SWITCHES & WIRING
    # ==========================================
    {
        "id": "prod_electrical_switch_17",
        "productId": "ELEC-SWT-01",
        "name": "Legrand Arteor 6A Modular Switch (Set of 10)",
        "category": "Switches & Wiring",
        "subcategory": "Modular Switches",
        "price": 149.00,
        "discountPrice": 129.00,
        "currency": "INR",
        "stock": 200,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.9,
        "reviews_count": 610,
        "reviewCount": 610,
        "badge": "Architectural",
        "image_url": "https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=600&auto=format&fit=crop&q=80",
        "description": "Premium glossy white modular switch with silver cadmium oxide contacts for 100,000+ operations and spark-free switching.",
        "specs": {
            "Rating": "6A 240V AC 1-Way",
            "Quantity": "Pack of 10 Units",
            "Contacts": "Silver Inlay High Conductivity",
            "Warranty": "10 Years Replacement",
        },
    },
    {
        "id": "prod_smart_switch_19",
        "productId": "ELEC-SWT-02",
        "name": "Sonoff WiFi 4-Gang Smart Touch Wall Switch",
        "category": "Switches & Wiring",
        "subcategory": "Smart Switches",
        "price": 1799.00,
        "discountPrice": 1599.00,
        "currency": "INR",
        "stock": 45,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.8,
        "reviews_count": 290,
        "reviewCount": 290,
        "badge": "Smart Touch",
        "image_url": "https://images.unsplash.com/photo-1558002038-1055907df827?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1558002038-1055907df827?w=600&auto=format&fit=crop&q=80",
        "description": "Tempered glass touch panel with WiFi and RF remote control. Alexa & Google Home compatible, timer scheduling.",
        "specs": {
            "Gangs": "4 Individual Channels",
            "Connectivity": "WiFi 2.4GHz + RF 433MHz",
            "Panel": "Toughened Crystal Glass",
            "Warranty": "2 Years",
        },
    },
    {
        "id": "prod_electrical_socket_18",
        "productId": "ELEC-SWT-03",
        "name": "Schneider Electric Livia 6/16A Combined Shuttered Socket",
        "category": "Switches & Wiring",
        "subcategory": "Electrical Sockets",
        "price": 199.00,
        "discountPrice": 169.00,
        "currency": "INR",
        "stock": 160,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.8,
        "reviews_count": 380,
        "reviewCount": 380,
        "badge": "Child Shutter",
        "image_url": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80",
        "description": "Dual 6A/16A universal modular socket with integrated child safety shutters and phosphor bronze spring contacts.",
        "specs": {
            "Rating": "6A / 16A Combined Heavy Load",
            "Modules": "2 Module Width",
            "Safety": "Child Protection Shutters",
            "Warranty": "5 Years",
        },
    },
    {
        "id": "prod_universal_socket_20",
        "productId": "ELEC-SWT-04",
        "name": "Anchor Roma Plus Multi-Country Universal Socket (16A)",
        "category": "Switches & Wiring",
        "subcategory": "Universal Sockets",
        "price": 249.00,
        "discountPrice": 219.00,
        "currency": "INR",
        "stock": 120,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.7,
        "reviews_count": 215,
        "reviewCount": 215,
        "badge": "Multi-Country",
        "image_url": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80",
        "description": "Universal pin socket accommodating UK, US, Euro, and Indian plugs with spark-shield internal architecture.",
        "specs": {
            "Rating": "16A 240V AC",
            "Compatibility": "US/UK/EU/IN Plugs",
            "Material": "UV Resistant Polycarbonate",
            "Warranty": "5 Years",
        },
    },
    {
        "id": "prod_mcb_19",
        "productId": "ELEC-SWT-05",
        "name": "Havells Euro-II 32A Double Pole C-Curve MCB",
        "category": "Switches & Wiring",
        "subcategory": "MCB & Circuit Breakers",
        "price": 599.00,
        "discountPrice": 529.00,
        "currency": "INR",
        "stock": 80,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.9,
        "reviews_count": 450,
        "reviewCount": 450,
        "badge": "IS/IEC Certified",
        "image_url": "https://images.unsplash.com/photo-1517646287270-a5a9ca602e5c?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1517646287270-a5a9ca602e5c?w=600&auto=format&fit=crop&q=80",
        "description": "32A Double Pole miniature circuit breaker with 10kA breaking capacity, bi-metallic overload strip, and rapid arc extinction chamber.",
        "specs": {
            "Poles": "Double Pole (DP)",
            "Current Rating": "32 Amperes",
            "Breaking Capacity": "10kA",
            "Warranty": "2 Years",
        },
    },
    {
        "id": "prod_dist_board_21",
        "productId": "ELEC-SWT-06",
        "name": "Schneider Acti9 8-Way Double Door MCB Distribution Board",
        "category": "Switches & Wiring",
        "subcategory": "Distribution Boards",
        "price": 1899.00,
        "discountPrice": 1699.00,
        "currency": "INR",
        "stock": 35,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.9,
        "reviews_count": 180,
        "reviewCount": 180,
        "badge": "IP43 Metallic",
        "image_url": "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=600&auto=format&fit=crop&q=80",
        "description": "8-way SPN double door distribution board with insulated busbar, neutral link, and earth bar in CRCA sheet steel.",
        "specs": {
            "Ways": "8-Way Single Phase Neutral",
            "Enclosure": "CRCA Steel with Powder Coating",
            "Protection": "IP43 Dust & Splash Resistant",
            "Warranty": "5 Years",
        },
    },

    # ==========================================
    # KITCHEN APPLIANCES
    # ==========================================
    {
        "id": "prod_electric_kettle_08",
        "productId": "ELEC-KIT-01",
        "name": "Prestige 1.5L Stainless Steel Fast-Boil Electric Kettle",
        "category": "Kitchen Appliances",
        "subcategory": "Electric Kettles",
        "price": 1299.00,
        "discountPrice": 1099.00,
        "currency": "INR",
        "stock": 70,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.7,
        "reviews_count": 310,
        "reviewCount": 310,
        "badge": "Fast Boil",
        "image_url": "https://images.unsplash.com/photo-1544233726-9f1d2b27be8b?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1544233726-9f1d2b27be8b?w=600&auto=format&fit=crop&q=80",
        "description": "1500W rapid boil electric kettle with automatic shut-off, boil-dry protection, 360-degree swivel base, and food-grade 304 steel.",
        "specs": {
            "Capacity": "1.5 Liters",
            "Power": "1500W",
            "Material": "304 Stainless Steel",
            "Safety": "Auto Cut-Off & Dry Boil Lock",
            "Warranty": "1 Year",
        },
    },
    {
        "id": "prod_mixer_grinder_09",
        "productId": "ELEC-KIT-02",
        "name": "Philips HL7756 750W Heavy-Duty Mixer Grinder (3 Jars)",
        "category": "Kitchen Appliances",
        "subcategory": "Mixer Grinders",
        "price": 6999.00,
        "discountPrice": 5999.00,
        "currency": "INR",
        "stock": 40,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.8,
        "reviews_count": 890,
        "reviewCount": 890,
        "badge": "Heavy Duty 750W",
        "image_url": "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=600&auto=format&fit=crop&q=80",
        "description": "Turbo 750W motor with advanced air ventilation to grind toughest spices in 2 minutes. Includes 3 stainless steel leak-proof jars.",
        "specs": {
            "Motor Power": "750W Turbo",
            "Jars": "1.5L Wet, 1.0L Multipurpose, 0.3L Chutney",
            "Overload Protection": "Yes",
            "Warranty": "2 Years Product, 5 Years Motor",
        },
    },
    {
        "id": "prod_induction_stove_10",
        "productId": "ELEC-KIT-03",
        "name": "Pigeon Cruise 2100W Digital Induction Cooktop",
        "category": "Kitchen Appliances",
        "subcategory": "Induction Stoves",
        "price": 3499.00,
        "discountPrice": 2999.00,
        "currency": "INR",
        "stock": 45,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.6,
        "reviews_count": 415,
        "reviewCount": 415,
        "badge": "Digital Touch",
        "image_url": "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&auto=format&fit=crop&q=80",
        "description": "7 preset Indian cooking menus, soft push button control, dual heat sensor, and LED display for high-efficiency energy-saving cooking.",
        "specs": {
            "Power": "2100W",
            "Presets": "7 Indian Cooking Modes",
            "Glass Plate": "High Grade Crystal Glass",
            "Warranty": "1 Year",
        },
    },
    {
        "id": "prod_toaster_22",
        "productId": "ELEC-KIT-04",
        "name": "Morphy Richards 2-Slice Pop-Up Auto-Eject Toaster 800W",
        "category": "Kitchen Appliances",
        "subcategory": "Toasters",
        "price": 1699.00,
        "discountPrice": 1499.00,
        "currency": "INR",
        "stock": 50,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.5,
        "reviews_count": 210,
        "reviewCount": 210,
        "badge": "Auto-Centering",
        "image_url": "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=600&auto=format&fit=crop&q=80",
        "description": "7 browning levels, defrost and reheat functions, removable crumb tray, and cool-touch body.",
        "specs": {
            "Power": "800W",
            "Capacity": "2-Slice Extra Wide Slots",
            "Features": "Defrost, Reheat, Cancel",
            "Warranty": "2 Years",
        },
    },

    # ==========================================
    # INVERTERS & HEAVY POWER
    # ==========================================
    {
        "id": "prod_inverter_21",
        "productId": "ELEC-INV-01",
        "name": "Luminous Zelio+ 1700 Pure Sinewave Smart Home Inverter",
        "category": "Inverters & Heavy Power",
        "subcategory": "Home Inverters",
        "price": 8499.00,
        "discountPrice": 7999.00,
        "currency": "INR",
        "stock": 30,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.9,
        "reviews_count": 560,
        "reviewCount": 560,
        "badge": "Pure Sine Wave",
        "image_url": "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=600&auto=format&fit=crop&q=80",
        "description": "1500VA / 24V Pure Sinewave smart home inverter system with intelligent 32-bit DSP processor and digital LCD backup time indicator.",
        "specs": {
            "Capacity": "1500VA / 1260W Output",
            "Waveform": "Pure Sine Wave",
            "Display": "Back-up time & battery % indicator",
            "Warranty": "2 Years Comprehensive",
        },
    },
    {
        "id": "prod_inverter_battery_23",
        "productId": "ELEC-INV-02",
        "name": "Exide Tubeler Plus 150Ah Heavy-Duty Tall Tubular Battery",
        "category": "Inverters & Heavy Power",
        "subcategory": "Inverter Batteries",
        "price": 16500.00,
        "discountPrice": 15499.00,
        "currency": "INR",
        "stock": 25,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.9,
        "reviews_count": 480,
        "reviewCount": 480,
        "badge": "60 Months Warranty",
        "image_url": "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=600&auto=format&fit=crop&q=80",
        "description": "150Ah tall tubular inverter battery with high acid volume and spine alloy technology for prolonged power cuts.",
        "specs": {
            "Capacity": "150Ah / 12V",
            "Technology": "Tall Tubular Deep Cycle",
            "Life Cycle": "1200+ Cycles at 80% DOD",
            "Warranty": "60 Months (36 Free + 24 Pro-rata)",
        },
    },
    {
        "id": "prod_ups_24",
        "productId": "ELEC-INV-03",
        "name": "APC Back-UPS 1100VA 230V Line Interactive UPS",
        "category": "Inverters & Heavy Power",
        "subcategory": "UPS",
        "price": 6799.00,
        "discountPrice": 6299.00,
        "currency": "INR",
        "stock": 35,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.8,
        "reviews_count": 390,
        "reviewCount": 390,
        "badge": "Automatic Voltage Reg",
        "image_url": "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&auto=format&fit=crop&q=80",
        "description": "1100VA / 660W line interactive battery backup UPS for desktop computers, gaming rigs, WiFi routers, and home entertainment.",
        "specs": {
            "Capacity": "1100VA / 660W",
            "Battery Backup": "Up to 50 Mins on Router/PC",
            "Outlets": "4 Battery Protected Outlets",
            "Warranty": "2 Years",
        },
    },
    {
        "id": "prod_stabilizer_25",
        "productId": "ELEC-INV-04",
        "name": "V-Guard VG 400 Voltage Stabilizer for 1.5 Ton AC",
        "category": "Inverters & Heavy Power",
        "subcategory": "Voltage Stabilizers",
        "price": 2499.00,
        "discountPrice": 2249.00,
        "currency": "INR",
        "stock": 50,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.8,
        "reviews_count": 420,
        "reviewCount": 420,
        "badge": "AC Protection",
        "image_url": "https://images.unsplash.com/photo-1517646287270-a5a9ca602e5c?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1517646287270-a5a9ca602e5c?w=600&auto=format&fit=crop&q=80",
        "description": "Intelligent digital voltage stabilizer with micro-controlled operation, high/low voltage cut-off, and thermal overload protection.",
        "specs": {
            "Working Range": "170V - 270V",
            "Application": "Up to 1.5 Ton Inverter/Split AC",
            "Time Delay": "3 Mins Smart Delay",
            "Warranty": "3 Years",
        },
    },
    {
        "id": "prod_industrial_panel_22",
        "productId": "ELEC-INV-05",
        "name": "Schneider Electric 3-Phase Industrial Distribution Panel 63A",
        "category": "Inverters & Heavy Power",
        "subcategory": "Industrial Power",
        "price": 75000.00,
        "discountPrice": 72000.00,
        "currency": "INR",
        "stock": 10,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 5.0,
        "reviews_count": 92,
        "reviewCount": 92,
        "badge": "Enterprise High Value",
        "image_url": "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=600&auto=format&fit=crop&q=80",
        "description": "Heavy industrial grade 3-Phase 415V electrical power distribution board with 63A 4-Pole RCCB, surge protection class II, and IP54 enclosure.",
        "specs": {
            "Voltage": "415V 3-Phase 50Hz",
            "Current Rating": "63A 4-Pole",
            "Enclosure": "IP54 Weatherproof Sheet Steel",
            "Protection": "Surge Diverter + 30mA Earth Leakage",
            "Warranty": "5 Years",
        },
    },

    # ==========================================
    # LAPTOPS & COMPUTERS
    # ==========================================
    {
        "id": "prod_laptop_entry_01",
        "productId": "LAP-001",
        "name": "Essential 15.6\" HD Everyday Laptop",
        "category": "Laptops & Computers",
        "subcategory": "Laptops",
        "price": 32999.00,
        "discountPrice": 29999.00,
        "currency": "INR",
        "stock": 25,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.5,
        "reviews_count": 140,
        "reviewCount": 140,
        "badge": "Budget Friendly",
        "image_url": "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&auto=format&fit=crop&q=80",
        "description": "Lightweight 15.6-inch laptop with Intel Quad Core processor, 8GB DDR4 RAM, 256GB SSD, and all-day 8-hour battery.",
        "specs": {
            "Processor": "Intel N4500 Quad-Core 2.8GHz",
            "RAM": "8GB DDR4 3200MHz",
            "Storage": "256GB PCIe NVMe SSD",
            "Display": "15.6\" HD Anti-Glare 220 nits",
            "OS": "Windows 11 Home",
            "Warranty": "1 Year On-Site",
        },
    },
    {
        "id": "prod_laptop_student_02",
        "productId": "LAP-002",
        "name": "ScholarBook 14\" Full HD Student Laptop",
        "category": "Laptops & Computers",
        "subcategory": "Laptops",
        "price": 45999.00,
        "discountPrice": 41999.00,
        "currency": "INR",
        "stock": 30,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.7,
        "reviews_count": 280,
        "reviewCount": 280,
        "badge": "Student Special",
        "image_url": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&auto=format&fit=crop&q=80",
        "description": "14-inch thin & light laptop engineered for students and coding with 12th Gen Core i3, 16GB RAM, 512GB SSD, and backlit keyboard.",
        "specs": {
            "Processor": "Intel Core i3-1215U (6 Cores, up to 4.4GHz)",
            "RAM": "16GB Dual-Channel DDR4",
            "Storage": "512GB Gen4 NVMe SSD",
            "Display": "14\" Full HD IPS Micro-Edge",
            "Weight": "1.38 kg",
            "Warranty": "2 Years",
        },
    },
    {
        "id": "prod_laptop_business_03",
        "productId": "LAP-003",
        "name": "ThinkPro 14\" Enterprise Business Ultrabook",
        "category": "Laptops & Computers",
        "subcategory": "Laptops",
        "price": 65999.00,
        "discountPrice": 62999.00,
        "currency": "INR",
        "stock": 20,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.9,
        "reviews_count": 420,
        "reviewCount": 420,
        "badge": "High Value / Priority",
        "image_url": "https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=600&auto=format&fit=crop&q=80",
        "description": "Military-grade certified business ultrabook with Intel Core i7 13th Gen, 16GB LPDDR5, 1TB SSD, Fingerprint & IR Face Recognition, and Thunderbolt 4.",
        "specs": {
            "Processor": "Intel Core i7-1355U (10 Cores, up to 5.0GHz)",
            "RAM": "16GB LPDDR5 5200MHz",
            "Storage": "1TB M.2 PCIe 4.0 SSD",
            "Display": "14\" 2.2K (2240x1400) IPS 100% sRGB",
            "Security": "dTPM 2.0 + Fingerprint Reader",
            "Warranty": "3 Years Premier Support",
        },
    },
    {
        "id": "prod_laptop_perf_04",
        "productId": "LAP-004",
        "name": "Precision Workstation 16\" Studio Creator Laptop",
        "category": "Laptops & Computers",
        "subcategory": "Laptops",
        "price": 89999.00,
        "discountPrice": 84999.00,
        "currency": "INR",
        "stock": 15,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.9,
        "reviews_count": 190,
        "reviewCount": 190,
        "badge": "High Value / Pro Studio",
        "image_url": "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=600&auto=format&fit=crop&q=80",
        "description": "Engineered for 3D modeling, video editing, and AI workflows. AMD Ryzen 7 7840HS, 32GB DDR5 RAM, 1TB Gen4 SSD, and NVIDIA RTX 4050 6GB GPU.",
        "specs": {
            "Processor": "AMD Ryzen 7 7840HS (8C/16T, up to 5.1GHz)",
            "Graphics": "NVIDIA GeForce RTX 4050 6GB GDDR6",
            "RAM": "32GB DDR5 5600MHz",
            "Storage": "1TB Gen4 NVMe (Dual M.2 slots)",
            "Display": "16\" 2.5K 165Hz 100% DCI-P3 500 nits",
            "Warranty": "3 Years Comprehensive",
        },
    },
    {
        "id": "prod_laptop_gaming_05",
        "productId": "LAP-005",
        "name": "Legion Apex 16\" QHD 165Hz Pro Gaming Laptop",
        "category": "Laptops & Computers",
        "subcategory": "Laptops",
        "price": 115000.00,
        "discountPrice": 109999.00,
        "currency": "INR",
        "stock": 12,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 5.0,
        "reviews_count": 310,
        "reviewCount": 310,
        "badge": "Extreme Gaming",
        "image_url": "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=600&auto=format&fit=crop&q=80",
        "description": "Flagship gaming battle-station powered by Intel Core i9-14900HX, NVIDIA RTX 4070 8GB (140W TGP), 32GB DDR5, Vapor Chamber cooling, and RGB per-key keyboard.",
        "specs": {
            "Processor": "Intel Core i9-14900HX (24 Cores, up to 5.8GHz)",
            "Graphics": "NVIDIA GeForce RTX 4070 8GB GDDR6 140W",
            "RAM": "32GB Dual-Channel DDR5 5600MHz",
            "Storage": "1TB PCIe Gen4 SSD (Upgradable)",
            "Display": "16\" WQXGA (2560x1600) 165Hz 3ms G-Sync",
            "Warranty": "3 Years On-Site + Accidental Damage",
        },
    },
    {
        "id": "prod_laptop_prem_06",
        "productId": "LAP-006",
        "name": "AeroBook Ultra 14\" 3K OLED Flagship Laptop",
        "category": "Laptops & Computers",
        "subcategory": "Laptops",
        "price": 145000.00,
        "discountPrice": 138000.00,
        "currency": "INR",
        "stock": 8,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 5.0,
        "reviews_count": 180,
        "reviewCount": 180,
        "badge": "Premium Flagship",
        "image_url": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&auto=format&fit=crop&q=80",
        "description": "Featherlight 990g carbon-fiber flagship laptop with 3K OLED 120Hz display, Intel Core Ultra 9 with dedicated NPU AI engine, 32GB RAM, and 2TB SSD.",
        "specs": {
            "Processor": "Intel Core Ultra 9 185H with AI NPU",
            "RAM": "32GB LPDDR5X 7467MHz",
            "Storage": "2TB NVMe PCIe 4.0 SSD",
            "Display": "14\" 3K (2880x1800) OLED 120Hz HDR 500",
            "Chassis": "CNC Aerospace Magnesium-Alloy (0.99kg)",
            "Warranty": "3 Years International VIP Support",
        },
    },

    # ==========================================
    # COMPUTER ACCESSORIES
    # ==========================================
    {
        "id": "prod_acc_mouse_01",
        "productId": "ACC-001",
        "name": "Ergonomic Silent 2.4G + Bluetooth Wireless Mouse",
        "category": "Computer Accessories",
        "subcategory": "Mice",
        "price": 899.00,
        "discountPrice": 749.00,
        "currency": "INR",
        "stock": 140,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.7,
        "reviews_count": 520,
        "reviewCount": 520,
        "badge": "Silent Clicks",
        "image_url": "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&auto=format&fit=crop&q=80",
        "description": "Dual-mode Bluetooth 5.0 and 2.4GHz wireless mouse with rechargeable battery, silent optical switches, and 2400 DPI precision.",
        "specs": {
            "Connectivity": "Bluetooth 5.0 + 2.4GHz USB Dongle",
            "DPI": "800 / 1200 / 1600 / 2400 DPI Adjustable",
            "Battery": "Rechargeable 500mAh Li-ion",
            "Warranty": "1 Year",
        },
    },
    {
        "id": "prod_acc_mouse_02",
        "productId": "ACC-002",
        "name": "Precision Optical 6-Button 3200 DPI Wired Mouse",
        "category": "Computer Accessories",
        "subcategory": "Mice",
        "price": 449.00,
        "discountPrice": 399.00,
        "currency": "INR",
        "stock": 160,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.5,
        "reviews_count": 310,
        "reviewCount": 310,
        "badge": "Budget Optical",
        "image_url": "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&auto=format&fit=crop&q=80",
        "description": "Braided USB wired optical mouse with 6 programmable buttons, ergonomic palm grip, and instant DPI cycling switch.",
        "specs": {
            "Sensor": "Gaming Optical 3200 DPI",
            "Buttons": "6 Clickable Switches",
            "Cable": "1.8M Braided Fiber Cord",
            "Warranty": "1 Year",
        },
    },
    {
        "id": "prod_acc_keyboard_03",
        "productId": "ACC-003",
        "name": "Slim Multi-Device Bluetooth & 2.4G Wireless Keyboard",
        "category": "Computer Accessories",
        "subcategory": "Keyboards",
        "price": 1499.00,
        "discountPrice": 1299.00,
        "currency": "INR",
        "stock": 90,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.8,
        "reviews_count": 430,
        "reviewCount": 430,
        "badge": "Multi-Device",
        "image_url": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80",
        "description": "Ultra-thin wireless scissor-switch keyboard pairing seamlessly across 3 devices (Laptop, Tablet, Phone) with unified shortcut keys.",
        "specs": {
            "Layout": "Full Size 104 Keys with NumPad",
            "Connectivity": "3 Channels (2x Bluetooth + 1x 2.4G)",
            "Battery Life": "Up to 12 Months",
            "Warranty": "2 Years",
        },
    },
    {
        "id": "prod_acc_keyboard_04",
        "productId": "ACC-004",
        "name": "Tenkeyless RGB Hot-Swappable Mechanical Keyboard",
        "category": "Computer Accessories",
        "subcategory": "Keyboards",
        "price": 3999.00,
        "discountPrice": 3499.00,
        "currency": "INR",
        "stock": 50,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.9,
        "reviews_count": 680,
        "reviewCount": 680,
        "badge": "Red Switches",
        "image_url": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80",
        "description": "87-key TKL mechanical keyboard with pre-lubed Red linear switches, per-key RGB backlighting, sound dampening foam, and detachable Type-C cable.",
        "specs": {
            "Switches": "Linear Red Mechanical (Hot-Swappable)",
            "Keycaps": "Double-Shot PBT Cherry Profile",
            "Lighting": "16.8M Per-Key RGB with 18 Modes",
            "Warranty": "2 Years",
        },
    },
    {
        "id": "prod_acc_cooling_05",
        "productId": "ACC-005",
        "name": "Dual 140mm Turbo Silent Fan RGB Laptop Cooling Pad",
        "category": "Computer Accessories",
        "subcategory": "Cooling & Stands",
        "price": 1299.00,
        "discountPrice": 1099.00,
        "currency": "INR",
        "stock": 70,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.6,
        "reviews_count": 270,
        "reviewCount": 270,
        "badge": "Turbo Cooling",
        "image_url": "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&auto=format&fit=crop&q=80",
        "description": "High-flow aluminum mesh cooling pad with two 1400 RPM silent fans, 6 adjustable height angles, phone holder, and dual USB passthrough.",
        "specs": {
            "Compatibility": "Fits 12\" to 17.3\" Laptops",
            "Fans": "2x 140mm Silent LED Fans",
            "Height Settings": "6 Ergonomic Incline Levels",
            "Warranty": "1 Year",
        },
    },
    {
        "id": "prod_acc_stand_06",
        "productId": "ACC-006",
        "name": "Ergonomic Aluminum Folding Multi-Angle Laptop Stand",
        "category": "Computer Accessories",
        "subcategory": "Cooling & Stands",
        "price": 999.00,
        "discountPrice": 849.00,
        "currency": "INR",
        "stock": 110,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.8,
        "reviews_count": 390,
        "reviewCount": 390,
        "badge": "All Metal CNC",
        "image_url": "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&auto=format&fit=crop&q=80",
        "description": "Precision sandblasted aircraft aluminum folding laptop stand with anti-slip silicone pads and ventilated hollow cooling design.",
        "specs": {
            "Material": "100% Solid Aluminum Alloy",
            "Weight Capacity": "Up to 10 kg",
            "Foldable": "Includes Travel Velvet Pouch",
            "Warranty": "3 Years",
        },
    },
    {
        "id": "prod_acc_charger_07",
        "productId": "ACC-007",
        "name": "Universal 100W GaN Type-C Fast Laptop Charger",
        "category": "Computer Accessories",
        "subcategory": "Power Adapters",
        "price": 1999.00,
        "discountPrice": 1699.00,
        "currency": "INR",
        "stock": 80,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.9,
        "reviews_count": 340,
        "reviewCount": 340,
        "badge": "100W GaN III",
        "image_url": "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&auto=format&fit=crop&q=80",
        "description": "Ultra-compact 100W GaN fast charger with 2x USB-C PD and 1x USB-A QC4+ ports. Simultaneously powers laptops, phones, and tablets.",
        "specs": {
            "Output": "100W Max Power Delivery 3.0",
            "Ports": "2x Type-C + 1x Type-A",
            "Compatibility": "MacBook, Dell, HP, Lenovo, Asus",
            "Warranty": "2 Years",
        },
    },
    {
        "id": "prod_acc_bag_08",
        "productId": "ACC-008",
        "name": "Water-Resistant Anti-Theft 15.6\" Laptop Backpack",
        "category": "Computer Accessories",
        "subcategory": "Bags & Sleeves",
        "price": 1499.00,
        "discountPrice": 1299.00,
        "currency": "INR",
        "stock": 75,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.7,
        "reviews_count": 280,
        "reviewCount": 280,
        "badge": "Anti-Theft",
        "image_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80",
        "description": "High-density waterproof oxford fabric backpack with padded laptop sleeve, external USB charging port, and hidden anti-theft pocket.",
        "specs": {
            "Capacity": "25 Liters / Fits up to 15.6\" Laptops",
            "Material": "Waterproof 900D Oxford Fabric",
            "Features": "Luggage Strap, USB Charging Pass",
            "Warranty": "1 Year",
        },
    },
    {
        "id": "prod_acc_usbhub_09",
        "productId": "ACC-009",
        "name": "4-Port USB 3.0 Ultra Slim Aluminum Hub (5Gbps)",
        "category": "Computer Accessories",
        "subcategory": "Hubs & Docks",
        "price": 799.00,
        "discountPrice": 649.00,
        "currency": "INR",
        "stock": 95,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.6,
        "reviews_count": 310,
        "reviewCount": 310,
        "badge": "5Gbps SuperSpeed",
        "image_url": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80",
        "description": "Instant 4-port USB 3.0 expansion with 5Gbps high-speed data transfer and smart over-current protection for flash drives, mice, and keyboards.",
        "specs": {
            "Ports": "4x USB 3.0 Type-A",
            "Data Rate": "Up to 5 Gbps (10x faster than USB 2.0)",
            "Chassis": "Anodized Aluminum",
            "Warranty": "2 Years",
        },
    },
    {
        "id": "prod_acc_webcam_10",
        "productId": "ACC-010",
        "name": "Pro 1080P Full HD Autofocus Webcam with Privacy Shutter",
        "category": "Computer Accessories",
        "subcategory": "Webcams",
        "price": 2499.00,
        "discountPrice": 2199.00,
        "currency": "INR",
        "stock": 65,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.8,
        "reviews_count": 360,
        "reviewCount": 360,
        "badge": "Full HD 1080P",
        "image_url": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80",
        "description": "Crisp 1080P 60FPS streaming webcam with dual noise-cancelling microphones, automatic low-light correction, and built-in physical privacy cover.",
        "specs": {
            "Resolution": "1080P Full HD @ 60FPS",
            "Field of View": "90° Wide Angle",
            "Microphone": "Dual Stereo Noise Reduction Mics",
            "Warranty": "2 Years",
        },
    },
    {
        "id": "prod_acc_hdd_11",
        "productId": "ACC-011",
        "name": "2TB Rugged Shock-Resistant USB 3.2 External Hard Drive",
        "category": "Computer Accessories",
        "subcategory": "Storage",
        "price": 5499.00,
        "discountPrice": 4999.00,
        "currency": "INR",
        "stock": 50,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.8,
        "reviews_count": 410,
        "reviewCount": 410,
        "badge": "Military Shockproof",
        "image_url": "https://images.unsplash.com/photo-1531492746076-161ca9bcad58?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1531492746076-161ca9bcad58?w=600&auto=format&fit=crop&q=80",
        "description": "Military-grade drop-tested 2TB portable external drive with USB 3.2 Gen 1 interface, automatic hardware encryption, and 3-year data rescue.",
        "specs": {
            "Capacity": "2 TB",
            "Interface": "USB 3.2 Gen 1 (Backwards Compatible)",
            "Durability": "IP54 Water/Dust & Shockproof",
            "Warranty": "3 Years Limited",
        },
    },
    {
        "id": "prod_acc_ssd_12",
        "productId": "ACC-012",
        "name": "1TB NVMe PCIe 4.0 Gen4 M.2 SSD (7000 MB/s)",
        "category": "Computer Accessories",
        "subcategory": "Storage",
        "price": 6999.00,
        "discountPrice": 6499.00,
        "currency": "INR",
        "stock": 45,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.9,
        "reviews_count": 520,
        "reviewCount": 520,
        "badge": "7000 MB/s Extreme",
        "image_url": "https://images.unsplash.com/photo-1531492746076-161ca9bcad58?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1531492746076-161ca9bcad58?w=600&auto=format&fit=crop&q=80",
        "description": "Blazing fast PCIe Gen 4x4 M.2 2280 internal solid state drive delivering up to 7000 MB/s read speeds with graphene heat dissipator.",
        "specs": {
            "Capacity": "1 TB",
            "Read / Write": "7000 MB/s Read / 6000 MB/s Write",
            "Form Factor": "M.2 2280 NVMe 1.4",
            "Warranty": "5 Years / 600 TBW",
        },
    },
    {
        "id": "prod_acc_ram_13",
        "productId": "ACC-013",
        "name": "16GB DDR5 5600MHz High-Performance Laptop RAM Module",
        "category": "Computer Accessories",
        "subcategory": "Memory (RAM)",
        "price": 4299.00,
        "discountPrice": 3899.00,
        "currency": "INR",
        "stock": 60,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.9,
        "reviews_count": 290,
        "reviewCount": 290,
        "badge": "DDR5 5600MHz",
        "image_url": "https://images.unsplash.com/photo-1531492746076-161ca9bcad58?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1531492746076-161ca9bcad58?w=600&auto=format&fit=crop&q=80",
        "description": "Next-generation 16GB DDR5 SODIMM laptop memory module running at 5600MHz with on-die ECC for rock-solid stability.",
        "specs": {
            "Capacity": "16 GB Single Module",
            "Speed": "DDR5-5600 PC5-44800",
            "Form Factor": "262-Pin SODIMM",
            "Warranty": "Lifetime Replacement",
        },
    },
    {
        "id": "prod_acc_monitor_14",
        "productId": "ACC-014",
        "name": "27-inch 4K UHD IPS Frameless Monitor (USB-C 65W PD)",
        "category": "Computer Accessories",
        "subcategory": "Monitors",
        "price": 24999.00,
        "discountPrice": 22999.00,
        "currency": "INR",
        "stock": 25,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.9,
        "reviews_count": 340,
        "reviewCount": 340,
        "badge": "4K IPS HDR400",
        "image_url": "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&auto=format&fit=crop&q=80",
        "description": "27-inch 3840x2160 4K UHD IPS professional monitor with 100% sRGB color gamut, HDR400, factory calibration, and single-cable 65W USB-C docking.",
        "specs": {
            "Screen Size": "27 Inch (68.6 cm)",
            "Resolution": "4K UHD 3840 x 2160 @ 60Hz",
            "Panel": "IPS Anti-Glare 10-Bit Color",
            "Ports": "USB-C (65W PD), 2x HDMI 2.0, DisplayPort 1.4",
            "Warranty": "3 Years On-Site",
        },
    },
    {
        "id": "prod_acc_hdmiadapter_15",
        "productId": "ACC-015",
        "name": "4K 60Hz USB-C to HDMI High-Speed Aluminum Adapter",
        "category": "Computer Accessories",
        "subcategory": "Cables & Adapters",
        "price": 499.00,
        "discountPrice": 429.00,
        "currency": "INR",
        "stock": 120,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.7,
        "reviews_count": 210,
        "reviewCount": 210,
        "badge": "4K 60Hz Display",
        "image_url": "https://images.unsplash.com/photo-1541689592655-f5f52825a3b8?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1541689592655-f5f52825a3b8?w=600&auto=format&fit=crop&q=80",
        "description": "Plug-and-play Type-C to HDMI adapter supporting 4K @ 60Hz resolution with gold-plated connectors and space gray aluminum alloy shell.",
        "specs": {
            "Output": "HDMI 2.0 (4K @ 60Hz / 2K @ 144Hz)",
            "Compatibility": "MacBook, iPad Pro, Windows Laptops, Smartphones",
            "Material": "Anodized Aluminum",
            "Warranty": "2 Years",
        },
    },
    {
        "id": "prod_acc_usbchub_16",
        "productId": "ACC-016",
        "name": "8-in-1 Aluminum USB-C Multiport Hub (100W PD + 4K HDMI)",
        "category": "Computer Accessories",
        "subcategory": "Hubs & Docks",
        "price": 1899.00,
        "discountPrice": 1699.00,
        "currency": "INR",
        "stock": 70,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 4.8,
        "reviews_count": 480,
        "reviewCount": 480,
        "badge": "8-in-1 Powerhouse",
        "image_url": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80",
        "description": "All-in-one docking dongle featuring 4K HDMI, 100W Power Delivery pass-through, Gigabit Ethernet LAN, 3x USB 3.0 ports, and SD/MicroSD card readers.",
        "specs": {
            "Ports": "1x 4K HDMI, 1x 100W PD, 1x RJ45 Gigabit, 3x USB 3.0, SD + TF",
            "Network": "1000 Mbps High Speed Ethernet",
            "Material": "CNC Aluminum",
            "Warranty": "2 Years",
        },
    },
    {
        "id": "prod_acc_dock_17",
        "productId": "ACC-017",
        "name": "Dual 4K Thunderbolt 4 / USB-C Laptop Docking Station",
        "category": "Computer Accessories",
        "subcategory": "Hubs & Docks",
        "price": 14999.00,
        "discountPrice": 13999.00,
        "currency": "INR",
        "stock": 18,
        "in_stock": True,
        "availability": "IN_STOCK",
        "rating": 5.0,
        "reviews_count": 160,
        "reviewCount": 160,
        "badge": "Thunderbolt 4 / 120W",
        "image_url": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80",
        "image": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80",
        "description": "Enterprise-grade 14-in-1 Thunderbolt 4 dock driving dual 4K @ 60Hz or single 8K displays with 120W dynamic host charging power supply.",
        "specs": {
            "Displays": "Dual 4K @ 60Hz / Single 8K @ 30Hz",
            "Host Power Delivery": "120W High Power Adapter Included",
            "Thunderbolt 4 Speed": "40 Gbps Bandwidth",
            "Warranty": "3 Years Comprehensive",
        },
    },
]

# Backward compatibility reference
ELECTRICAL_PRODUCTS = CATALOG_ITEMS


def seed_products_if_needed(db: Session) -> None:
    """Seeds products into database if the products table is empty."""
    try:
        count = db.scalar(select(Product).limit(1))
        if count is None:
            for item in CATALOG_ITEMS:
                prod = Product(
                    id=item["id"],
                    name=item["name"],
                    category=item["category"],
                    subcategory=item.get("subcategory"),
                    description=item["description"],
                    price=Decimal(str(item["price"])),
                    discount_price=Decimal(str(item.get("discountPrice", item["price"]))),
                    stock=item.get("stock", 100),
                    image_url=item["image_url"],
                    rating=float(item.get("rating", 4.5)),
                    reviews_count=item.get("reviews_count", 50),
                    badge=item.get("badge"),
                    specifications=item.get("specs", {}),
                    availability=item.get("availability", "IN_STOCK"),
                )
                db.add(prod)
            db.commit()
    except Exception as e:
        db.rollback()
        # Fallback to in-memory catalog
        pass


def list_products(
    category: str | None = None,
    search: str | None = None,
    db: Session | None = None,
) -> list[dict[str, Any]]:
    """
    Returns products filtered by category and/or search term.
    Queries database first, falling back to memory catalog.
    """
    results: list[dict[str, Any]] = []

    # If DB session provided or can be created, try fetching from DB
    should_close_db = False
    if db is None:
        try:
            db = SessionLocal()
            should_close_db = True
        except Exception:
            db = None

    if db is not None:
        try:
            seed_products_if_needed(db)
            query = select(Product)
            if category and category.strip().lower() != "all":
                cat = category.strip()
                query = query.where(Product.category.ilike(f"%{cat}%"))
            if search and search.strip():
                s = f"%{search.strip()}%"
                query = query.where(
                    or_(
                        Product.name.ilike(s),
                        Product.description.ilike(s),
                        Product.category.ilike(s),
                        Product.subcategory.ilike(s),
                    )
                )
            db_products = db.scalars(query).all()
            if db_products:
                for p in db_products:
                    results.append(
                        {
                            "id": p.id,
                            "productId": p.id,
                            "name": p.name,
                            "category": p.category,
                            "subcategory": p.subcategory or "",
                            "price": float(p.price),
                            "discountPrice": float(p.discount_price) if p.discount_price else float(p.price),
                            "currency": "INR",
                            "stock": p.stock,
                            "in_stock": p.stock > 0,
                            "availability": p.availability or "IN_STOCK",
                            "rating": float(p.rating),
                            "reviews_count": p.reviews_count,
                            "reviewCount": p.reviews_count,
                            "badge": p.badge,
                            "image_url": p.image_url,
                            "image": p.image_url,
                            "description": p.description,
                            "specs": p.specifications or {},
                            "createdAt": p.created_at.isoformat() if p.created_at else None,
                            "updatedAt": p.updated_at.isoformat() if p.updated_at else None,
                        }
                    )
                return results
        except Exception:
            pass
        finally:
            if should_close_db and db is not None:
                db.close()

    # Fallback to in-memory catalog
    results = CATALOG_ITEMS
    if category and category.strip().lower() != "all":
        cat_lower = category.strip().lower()
        results = [p for p in results if cat_lower in p["category"].lower() or cat_lower in (p.get("subcategory") or "").lower()]
    if search and search.strip():
        s = search.strip().lower()
        results = [
            p
            for p in results
            if s in p["name"].lower()
            or s in p["description"].lower()
            or s in p["category"].lower()
            or s in (p.get("subcategory") or "").lower()
        ]
    return results


def get_product_by_id(product_id: str, db: Session | None = None) -> dict[str, Any] | None:
    """Finds product by ID from DB or catalog."""
    if db is not None:
        try:
            p = db.scalar(select(Product).where(Product.id == product_id))
            if p:
                return {
                    "id": p.id,
                    "productId": p.id,
                    "name": p.name,
                    "category": p.category,
                    "subcategory": p.subcategory or "",
                    "price": float(p.price),
                    "discountPrice": float(p.discount_price) if p.discount_price else float(p.price),
                    "currency": "INR",
                    "stock": p.stock,
                    "in_stock": p.stock > 0,
                    "availability": p.availability or "IN_STOCK",
                    "rating": float(p.rating),
                    "reviews_count": p.reviews_count,
                    "reviewCount": p.reviews_count,
                    "badge": p.badge,
                    "image_url": p.image_url,
                    "image": p.image_url,
                    "description": p.description,
                    "specs": p.specifications or {},
                    "createdAt": p.created_at.isoformat() if p.created_at else None,
                    "updatedAt": p.updated_at.isoformat() if p.updated_at else None,
                }
        except Exception:
            pass

    # Match in CATALOG_ITEMS
    for p in CATALOG_ITEMS:
        if p["id"] == product_id or p.get("productId") == product_id:
            return p
    return None


def deduct_product_stock(product_id: str, quantity: int, db: Session) -> bool:
    """Deduct product stock in database upon successful order confirmation."""
    try:
        prod = db.scalar(select(Product).where(Product.id == product_id))
        if prod:
            prod.stock = max(0, prod.stock - quantity)
            if prod.stock == 0:
                prod.availability = "OUT_OF_STOCK"
            db.commit()
            return True
    except Exception:
        db.rollback()
    return False


def calculate_risk_level(amount: float, failure_type: str, retry_count: int) -> dict[str, Any]:
    """
    Transparent Risk Evaluation Algorithm:
    - Order Amount:
        < ₹1,000 -> LOW (e.g. LED bulbs, USB cables)
        ₹1,000 - ₹10,000 -> MEDIUM (e.g. Ceiling fans, Power strips, Kettles)
        ₹10,000 - ₹50,000 -> HIGH (e.g. Inverters, Entry Laptops, Monitors)
        >= ₹50,000 -> CRITICAL / HIGH PRIORITY (e.g. Business Laptops ₹65,999, Workstations ₹89k, Gaming ₹1.15L)
    - Multipliers for failure type and attempts.
    """
    if amount < 1000:
        base_score = 0.25
        risk_level = "LOW"
    elif amount < 10000:
        base_score = 0.55
        risk_level = "MEDIUM"
    elif amount < 50000:
        base_score = 0.85
        risk_level = "HIGH"
    else:
        base_score = 0.98
        risk_level = "CRITICAL"

    if failure_type.upper() in {"NETWORK_ERROR", "PAYMENT_TIMEOUT"}:
        recommendation = f"High priority recovery: {risk_level} value order (₹{amount:,.2f}) experienced transient technical failure. Automated secure retry link generated."
        recoverability = "HIGH"
    elif failure_type.upper() == "CHECKOUT_ABANDONMENT":
        recommendation = f"High purchase intent detected: Customer reached payment for ₹{amount:,.2f}. Sent reservation recovery message."
        recoverability = "MEDIUM"
    elif retry_count >= 1:
        recommendation = f"Repeated payment failure ({retry_count + 1} attempts). Immediate human associate intervention required."
        recoverability = "MANUAL_REQUIRED"
    else:
        recommendation = f"Assess payment channel for {risk_level} risk order value of ₹{amount:,.2f}."
        recoverability = "MODERATE"

    return {
        "risk_level": risk_level,
        "risk_score": base_score,
        "recommendation": recommendation,
        "recoverability": recoverability,
    }
